language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - yarn install
script:
  - yarn test
  - yarn rollup
deploy:
  provider: npm
  skip_cleanup: true
  email: elia.camposilvan@gmail.com
  api_key: $NPM_TOKEN
  tag: next
  script: bash deploy.sh
  on:
    tags: true
    repo: asulta/js-storage-wrap
