language: node_js
node_js:
  - '8'
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - yarn install
script:
  - yarn test
  - yarn rollup
  - npm whoami
  - npm publish
deploy:
  provider: npm
  email: elia.camposilvan@gmail.com
  api_key: $NPM_TOKEN
  tag: next
  on:
    tags: true
    branch: master
    repo: asulta/storage-wrap
