language: node_js
node_js:
  - '8'
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - yarn install
script:
  - yarn test
  - yarn rollup
deploy:
  provider: npm
  skip_cleanup: true
  email: elia.camposilvan@gmail.com
  api_key: $NPM_TOKEN
  tag: next
  script: bash deploy.sh
  on:
    tags: true
    repo: asulta/storage-wrap
